///for MIME types by magic value @ offset
#include <unistd.h>


typedef struct MIMEtype{
	const char *major;
	const char *minor;
}MIMEtype;


#ifndef NO_MAGIC
/*TODO
 * Add {le,be}{short,long} - be* is correct order, le* is reversed by byte
 * 	
 * Add magics at uncommon offsets
 */

typedef struct {
	const unsigned char *magic;
	MIMEtype type;
	unsigned int len;
} MIMEMagic;

static const MIMEMagic mimes0[] = { /*sorted by magic in ascii order @ offset 0 for memcmp ...A-Z comes before a-z*/
	/** @ offset of 0 **/
	{"\000\001\000\000\000",(MIMEtype){"application","x-font-ttf"},5},
	{"\004%!PS-Adobe-",(MIMEtype){"application","postscript"},12},
	{"\033%-12345X%!PS",(MIMEtype){"application","postscript"},9},
	{"\037\213",(MIMEtype){"application","x-gzip"},2},
	{"\037\235",(MIMEtype){"application","x-compress"},2},
	{"!<arch>\ndebian",(MIMEtype){"application","x-debian-package"},14},
	{"#! rnews",(MIMEtype){"message","rfc822"},8},
	{"#!/bin/ash",(MIMEtype){"application","x-shellscript"},10},
	{"#!/bin/bash",(MIMEtype){"application","x-shellscript"},11},
	{"#!/bin/perl",(MIMEtype){"text","x-perl"},11},
	{"#!/bin/sh",(MIMEtype){"application","x-shellscript"},9},
	{"#!/usr/bin/env lua",(MIMEtype){"text","x-lua"},18},
	{"#!/usr/bin/perl",(MIMEtype){"text","x-perl"},15},
	{"#!/usr/bin/env python",(MIMEtype){"text","x-python"},21},
	{"#!/usr/bin/env ruby",(MIMEtype){"text","x-ruby"},19},
	{"#!/usr/bin/env tcl",(MIMEtype){"text","x-tcl"},18},
	{"#!/usr/bin/env wish",(MIMEtype){"text","x-tcl"},19},
	{"#!/usr/bin/lua",(MIMEtype){"text","x-lua"},14},
	{"#!/usr/bin/python",(MIMEtype){"text","x-python"},17},
	{"#!/usr/bin/ruby",(MIMEtype){"text","x-ruby"},15},
	{"#!/usr/bin/tcl",(MIMEtype){"text","x-tcl"},14},
	{"#!/usr/bin/wish",(MIMEtype){"text","x-tcl"},15},
	{"#!/usr/local/bin/lua",(MIMEtype){"text","x-lua"},20},
	{"#!/usr/local/bin/perl",(MIMEtype){"text","x-perl"},21},
	{"#!/usr/local/bin/python",(MIMEtype){"text","x-python"},21},
	{"#!/usr/local/bin/ruby",(MIMEtype){"text","x-ruby"},21},
	{"#!/usr/local/bin/tcl",(MIMEtype){"text","x-tcl"},20},
	{"#!/usr/local/bin/wish",(MIMEtype){"text","x-tcl"},21},
	{"# KDE Config File",(MIMEtype){"application","x-kdelnk"},19},
	{"# PaCkAgE DaTaStReAm",(MIMEtype){"application","x-svr4-package"},20},
	{"# xmcd",(MIMEtype){"text","x-xmcd"},6},
	{"#?RADIANCE\n",(MIMEtype){"image","vnd.radiance"},11},
	{"%!PS-Adobe-",(MIMEtype){"application","postscript"},11},
	{"%PDF-",(MIMEtype){"application","pdf"},5}, // also "%FDF-" ???
	{"*mbx*",(MIMEtype){"application","mbox"},5}, //not sure ???
	{"-----BEGIN\040PGP\40MESSAGE-",(MIMEtype){"application","pgp"},28},
	{"-----BEGIN\040PGP\40SIGNATURE-",(MIMEtype){"application","pgp-signature"},30},
	{".\\\"",(MIMEtype){"text","troff"},3},
	{".sd\0",(MIMEtype){"audio","x-dec-basic"},4},
	{".snd",(MIMEtype){"audio","basic"},4},
	{"/* XPM */",(MIMEtype){"image","x-xpmi"},9},
	{"07070",(MIMEtype){"application","x-cpio"},5},
	{"1\xbe\0\0",(MIMEtype){"application","msword"},4},
	{"7z\274\257\047\034",(MIMEtype){"application","x-7z-compressed"},6},
	{"8BPS Adobe Photoshop Image",(MIMEtype){"image","vnd.adobe.photoshop"},26},
	{";ELC",(MIMEtype){"application","x-elc"},4},
	{"<!DOCTYPE HTML",(MIMEtype){"text","html"},14},
	{"<?xml version=",(MIMEtype){"application","xml"},14}, //TODO ... need to strcasestr for html,svg,etc...
	{"<Book ",(MIMEtype){"application","x-mif"},6},
	{"<BookFile",(MIMEtype){"application","x-mif"},9},
	{"<MML",(MIMEtype){"application","x-mif"},4},
	{"<MIFFile",(MIMEtype){"application","x-mif"},8},
	{"<MakerDictionary",(MIMEtype){"application","x-mif"},16},
	{"<Maker",(MIMEtype){"application","x-mif"},6},
	{"<SCRIBUSUTF8",(MIMEtype){"application","x-scribus"},12},
	{"<map version",(MIMEtype){"application","x-freemind"},12},
	{"@ echo off",(MIMEtype){"text","x-msdos-batch"},10},
	{"@echo off",(MIMEtype){"text","x-msdos-batch"},9},
	{"@rem",(MIMEtype){"text","x-msdos-batch"},4},
	{"@set",(MIMEtype){"text","x-msdos-batch"},4},
	{"ADIF",(MIMEtype){"audio","x-hx-aac-adif"},4},
	{"AT&TFORM",(MIMEtype){"image","vnd.djvu"},8},
	{"Article",(MIMEtype){"message","news"},7},
	{"BEGIN:VCALENDAR",(MIMEtype){"text","calendar"},15},
	{"BEGIN:VCARD",(MIMEtype){"text","x-vcard"},11},
	{"BM",(MIMEtype){"image","x-ms-bmp"},4},
	{"BZh",(MIMEtype){"application","x-bzip2"},3},
	{"CPC\262",(MIMEtype){"image","x-cpi"},4},
	{"CWS",(MIMEtype){"application","x-shockwave-flash"},3},
	{"DICM ",(MIMEtype){"application","dicom"},4},
	{"EIM ",(MIMEtype){"image","x-eim"},4},
	{"FGF95a",(MIMEtype){"image","x-unknown"},6},
	{"FLV",(MIMEtype){"video","x-flv"},3},
	{"FOVb",(MIMEtype){"image","x-x3f"},4},
	{"FWS",(MIMEtype){"application","x-shockwave-flash"},3},
	{"Forward to",(MIMEtype){"message","rfc822"},10},
	{"From:",(MIMEtype){"message","rfc822"},5},
	{"GIF8",(MIMEtype){"image","gif"},4},
	{"GIF94z",(MIMEtype){"image","x-unknown"},6},
	{"HEADER    ",(MIMEtype){"chemical","x-pdb"},10},
	{"HWP Document File",(MIMEtype){"application","x-hwp"},17},
	{"II\x1a\0\0\0HEAPCCDR",(MIMEtype){"image","x-canon-crw"},14},
	{"II*\0",(MIMEtype){"image","tiff"},4}, //wtf, this can override next one
	{"II*\0\x10\0\0\0CR",(MIMEtype){"image","x-canon-cr2"},10},
	{"IIN1",(MIMEtype){"image","x-niff"},4},
	{"IIRO",(MIMEtype){"image","x-olympus-orf"},4},
	{"IIRS",(MIMEtype){"image","x-olympus-orf"},4},
	{"LRZI",(MIMEtype){"application","x-lrzip"},4},
	{"LZIP",(MIMEtype){"application","x-lzip"},4},
	{"MAS_UTrack_V00",(MIMEtype){"audio","x-mod"},14},
	{"MM\0*",(MIMEtype){"image","tiff"},4},
	{"MMOR",(MIMEtype){"image","x-olympus-orf"},4},
	{"MOVI",(MIMEtype){"video","x-sgi-movie"},4},
	{"MThd",(MIMEtype){"audio","midi"},4},
	{"MZ",(MIMEtype){"application","x-dosexec"},2},
	{"N#! rnews",(MIMEtype){"message","rfc822"},9},
	{"OTTO",(MIMEtype){"application","vnd.ms-opentype"},4},
	{"OggS",(MIMEtype){"application","ogg"},4},
	{"P4\0",(MIMEtype){"image","x-portable-bitmap"},3},
	{"P5\0",(MIMEtype){"image","x-portable-greymap"},3},
	{"P6\0",(MIMEtype){"image","x-portable-pixmap"},3},
	{"P7\0",(MIMEtype){"image","x-portable-pixmap"},3},
	{"PBF",(MIMEtype){"image","x-unknown"},3},
	{"PDN3",(MIMEtype){"image","x-paintnet"},4},
	{"PFS1\x0a",(MIMEtype){"image","x-pfs"},5},
	{"PK\003\004",(MIMEtype){"application","zip"},4},
	{"PK\x07\x08PK\x03\x04",(MIMEtype){"application","zip"},8},
	{"PK00PK\003\004",(MIMEtype){"application","zip"},8},
	{"PO^Q`",(MIMEtype){"application","msword"},5}, // "\376\067\0\043"}, \333\245-\0\0\0
	{"Path:",(MIMEtype){"message","news"},5},
	{"Pipe to",(MIMEtype){"message","rfc822"},7},
	{"RF64\xff\xff\xff\xffWAVEds64",(MIMEtype){"audio","x-wav"},16},
	{"Rar!",(MIMEtype){"application","x-rar"},4},
	{"Received:",(MIMEtype){"message","rfc822"},9},
	{"Relay-Version:",(MIMEtype){"message","rfc822"},14},
	{"Return-Path:",(MIMEtype){"message","rfc822"},12},
	{"SIT!",(MIMEtype){"application","x-stuffit"},4},
	{"SplineFontDB:",(MIMEtype){"application","vnd.font-fontforge-sfd"},13},
	{"StuffIt",(MIMEtype){"application","x-stuffit"},8},
	{"WARC",(MIMEtype){"application","warc"},},
	{"Xcur",(MIMEtype){"image","x-xcursor"},4},
	{"Xref:",(MIMEtype){"message","news"},},
	{"[KDE Desktop Entry]",(MIMEtype){"application","x-kdelnk"},19},
	{"d8:announce",(MIMEtype){"application","x-bittorrent"},11},
	{"drpm",(MIMEtype){"application","x-rpm"},4},
	{"fLaC",(MIMEtype){"audio","x-flac"},4},
	{"filedesc://",(MIMEtype){"application","x-ia-arc"},11},
	{"riff\x2E\x91\xCF\x11\xA5\xD6\x28\xDB\x04\xC1\x00\x00",(MIMEtype){"audio","x-w64"},16},
	{"{\\rtf",(MIMEtype){"text","rtf"},5},
	{"\x89LZO\0\r\n\x1a\n",(MIMEtype){"application","x-lzop"},9},
	{"\x89PNG\r\n\x1a\n",(MIMEtype){"image","png"},8},
	{"\x8aJNG",(MIMEtype){"video","x-jng"},4},
	{"\x8aMNG",(MIMEtype){"video","x-mng"},4},
	{"\211HDF\r\n\032\n",(MIMEtype){"application","x-hdf"},8},
	{"\xce\xce\xce\xce",(MIMEtype){"application","x-java-jce-keystore"},4},
	{"\xfd""7zXZ\0",(MIMEtype){"application","x-xz"},6},
	{"\xfe\067\0\043",(MIMEtype){"application","msword"},4},
	{"\xff\xd8",(MIMEtype){"image","jpeg"},2},
	{"\xff\330\377\340",(MIMEtype){"image","jpeg"},4},
	{"\xff\330\377\356",(MIMEtype){"image","jpeg"},4},
	
};

static const MIMEMagic mimes4[] = { /*sorted by magic in ascii order @ offset 4 for memcmp ...A-Z comes before a-z*/
	/** @ offset of 4 **/
	{"\x0AVersion:Vivo",(MIMEtype){"video","vivo"},13},
	{"#VRML V",(MIMEtype){"model","vrml"},7},
	{"-BEGIN PGP PUBLIC KEY BLOCK-",(MIMEtype){"application","pgp-keys"},28},
	{"XPR3",(MIMEtype){"application","x-quark-xpress-3"},4},
	{"XPRa",(MIMEtype){"application","x-quark-xpress-3"},4},
	{"free",(MIMEtype){"video","quicktime"},4},
	{"ftyp3g2",(MIMEtype){"video","3gpp2"},7},
	{"ftyp3ge",(MIMEtype){"video","3gpp"},7},
	{"ftyp3gg",(MIMEtype){"video","3gpp"},7},
	{"ftyp3gp",(MIMEtype){"video","3gpp"},7},
	{"ftyp3gs",(MIMEtype){"video","3gpp"},7},
	{"ftypM4A",(MIMEtype){"audio","mp4"},7},
	{"ftypM4B",(MIMEtype){"video","quicktime"},7},
	{"ftypM4P",(MIMEtype){"video","quicktime"},7},
	{"ftypM4V",(MIMEtype){"video","mp4"},7},
	{"ftypavc1",(MIMEtype){"video","3gpp"},8},
	{"ftypiso2",(MIMEtype){"video","mp4"},8},
	{"ftypisom",(MIMEtype){"video","mp4"},8},
	{"ftypjp2",(MIMEtype){"image","jp2"},7},
	{"ftypmmp4",(MIMEtype){"video","mp4"},8},
	{"ftypmp41",(MIMEtype){"video","mp4"},8},
	{"ftypmp42",(MIMEtype){"video","mp4"},8},
	{"ftypmp7b",(MIMEtype){"video","mp4"},8},
	{"ftypmp7t",(MIMEtype){"video","mp4"},8},
	{"ftypqt",(MIMEtype){"video","quicktime"},6},
	{"idat",(MIMEtype){"video","quicktime"},4},
	{"idsc",(MIMEtype){"video","quicktime"},4},
	{"jP",(MIMEtype){"image","jp2"},2},
	{"mdat",(MIMEtype){"video","quicktime"},4},
	{"pckg",(MIMEtype){"application","x-quicktime-player"},4},
	{"skip",(MIMEtype){"video","quicktime"},4},
	{"wide",(MIMEtype){"video","quicktime"},4},
};

static const MIMEMagic mimes8[] = { /*sorted by magic in ascii order @ offset 8 for memcmp ...A-Z comes before a-z*/
	/** @ offset of 8 TODO **/
	{"",(MIMEtype){"",""},0},
};

/**	extra_mimes are sorted by offset to allow using the same buf[] used to
 * stream data in pipes so it can skip offsets outside the input buffer range.
 * This may take multiple passes to find if small buffers are used and may
 * fail if a magic string spans across the boundary
 * Note: web servers need to prepend the mime type to the data using:
 * Content-type: ... so in order to allow a continuous stream,
 * the buffer should be large enough to reach all magics in the 1st go or rely
 * on extension based results.
 */
static const struct {	//must do linear search on these
	const unsigned char *magic;
	MIMEtype type;
	unsigned short len;
	unsigned short offset;
} extra_mimes[]={
	{"Microsoft Word 6.0 Document",(MIMEtype){"application","msword"},27,2080},
	{"Documento Microsoft Word 6",(MIMEtype){"application","msword"},26,2080},
	{"Microsoft Excel 5.0 Worksheet",(MIMEtype){"application","vnd.ms-excel"},29,2080},
	{"Foglio di lavoro Microsoft Exce",(MIMEtype){"application","vnd.ms-excel"},31,2080},
	{"MSWordDoc",(MIMEtype){"application","msword"},9,2112},
	{"CD001",(MIMEtype){"application","x-iso9660-image"},5,32769},
};

MIMEtype *mime_search(const MIMEMagic *mimes,int count,int offset,const char *buf){
	int i=count>>1,bot=0,top=count,cmp;
	for (; bot<=top; i=(bot+top)>>1){
		cmp=memcmp(buf+offset,mimes[i].magic,mimes[i].len);
		if (! cmp) return (MIMEtype *)&mimes[i].type; //match found
		else if (cmp>0) bot=i+1;
		else top=i-1;
	}
	return (MIMEtype *)NULL;
}

MIMEtype *mime_find(const char *buf,int offset, int len){
//TODO
	int i;
	for(i=0;i<(sizeof(extra_mimes)/sizeof(extra_mimes[0]));i++){
		if (offset > extra_mimes[i].offset) continue;
		if (offset+len < extra_mimes[i].offset) return (MIMEtype *)NULL;
		if (!memcmp(buf+(extra_mimes[i].offset-offset),extra_mimes[i].magic,extra_mimes[i].len))
			return (MIMEtype *)&extra_mimes[i].type;
	}
	return (MIMEtype *)NULL;
}


MIMEtype *mime_from_magic(int fd){
	#define BUFLEN 32 //must be larger than max offset + max magic length
	char buf[BUFLEN];
	MIMEtype *ret=NULL;
	if (!fd || (read(fd,buf,BUFLEN) < BUFLEN))
		return (MIMEtype *)NULL;
	// do the faster binary searches first for the common offsets
	ret = mime_search(mimes0,(sizeof(mimes0)/sizeof(mimes0[0])-1),0,buf);
	if (ret != (MIMEtype *)NULL) return ret;
	else return mime_search(mimes4,(sizeof(mimes4)/sizeof(mimes4[0])-1),4,buf);
	//if (ret!=NULL) return ret;
	// TODO mime_find last since it must be a slower linear search
	//return (MIMEtype){"",""};
}
#endif


///for MIME types by file extension
static const struct {const char* ext;MIMEtype type;} mimes[] = {
	//{"",(MIMEtype){"inode","directory"}}, //assumes passed basename of a directory path
	{"/",(MIMEtype){"inode","directory"}},//uncomment and comment "" if ","s are handled
	{"123",(MIMEtype){"application","vnd.lotus-1-2-3"}},
	{"2fs",(MIMEtype){"application","x-ext2-image"}},
	{"323",(MIMEtype){"text","h323"}},
	{"3ds",(MIMEtype){"image","x-3ds"}},
	{"3fs",(MIMEtype){"application","x-ext3-image"}},
	{"3g2",(MIMEtype){"video","3gpp"}},
	{"3ga",(MIMEtype){"video","3gpp"}},
	{"3gp",(MIMEtype){"video","3gpp"}},
	{"3gpp",(MIMEtype){"video","3gpp"}},
	{"4fs",(MIMEtype){"application","x-ext4-image"}},
	{"602",(MIMEtype){"application","x-t602"}},
	{"669",(MIMEtype){"audio","x-mod"}},
	{"7z",(MIMEtype){"application","x-7z-compressed"}},
	{"a",(MIMEtype){"application","x-archive"}},
	{"aac",(MIMEtype){"audio","mp4"}},
	{"abw",(MIMEtype){"application","x-abiword"}},
	{"abw.gz",(MIMEtype){"application","x-abiword"}},
	{"ac3",(MIMEtype){"audio","ac3"}},
	{"ace",(MIMEtype){"application","x-ace"}},
	{"acx",(MIMEtype){"application","internet-property-stream"}},
	{"adb",(MIMEtype){"text","x-adasrc"}},
	{"ads",(MIMEtype){"text","x-adasrc"}},
	{"afm",(MIMEtype){"application","x-font-afm"}},
	{"ag",(MIMEtype){"image","x-applix-graphics"}},
	{"ai",(MIMEtype){"application","illustrator"}},
	{"aif",(MIMEtype){"audio","x-aiff"}},
	{"aifc",(MIMEtype){"audio","x-aiff"}},
	{"aiff",(MIMEtype){"audio","x-aiff"}},
	{"al",(MIMEtype){"application","x-perl"}},
	{"alz",(MIMEtype){"application","x-alz"}},
	{"amr",(MIMEtype){"audio","AMR"}},
	{"amz",(MIMEtype){"audio","x-amzxml"}},
	{"ani",(MIMEtype){"application","x-navi-animation"}},
	{"anim",(MIMEtype){"video","x-anim"}},
	{"anim0",(MIMEtype){"video","x-anim"}},
	{"anim1",(MIMEtype){"video","x-anim"}},
	{"anim2",(MIMEtype){"video","x-anim"}},
	{"anim3",(MIMEtype){"video","x-anim"}},
	{"anim4",(MIMEtype){"video","x-anim"}},
	{"anim5",(MIMEtype){"video","x-anim"}},
	{"anim6",(MIMEtype){"video","x-anim"}},
	{"anim7",(MIMEtype){"video","x-anim"}},
	{"anim8",(MIMEtype){"video","x-anim"}},
	{"anim9",(MIMEtype){"video","x-anim"}},
	{"animj",(MIMEtype){"video","x-anim"}},
	{"anx",(MIMEtype){"application","annodex"}},
	{"ape",(MIMEtype){"audio","x-ape"}},
	{"arj",(MIMEtype){"application","x-arj"}},
	{"arw",(MIMEtype){"image","x-sony-arw"}},
	{"as",(MIMEtype){"application","x-applix-spreadsheet"}},
	{"asc",(MIMEtype){"text","plain"}},//{"asc",(MIMEtype){"application","pgp-encrypted"}},//{"asc",(MIMEtype){"application","pgp-keys"}},
	{"asf",(MIMEtype){"video","x-ms-asf"}},
	{"asp",(MIMEtype){"application","x-asp"}},
	{"asr",(MIMEtype){"video","x-ms-asf"}},
	{"ass",(MIMEtype){"text","x-ssa"}},
	{"asx",(MIMEtype){"audio","x-ms-asx"}},
	{"atom",(MIMEtype){"application","atom+xml"}},
	{"au",(MIMEtype){"audio","basic"}},
	{"authors",(MIMEtype){"text","x-authors"}},
	{"avi",(MIMEtype){"video","x-msvideo"}},
	{"aw",(MIMEtype){"application","x-applix-word"}},
	{"awb",(MIMEtype){"audio","AMR-WB"}},
	{"awk",(MIMEtype){"application","x-awk"}},
	{"axa",(MIMEtype){"audio","annodex"}},
	{"axs",(MIMEtype){"application","olescript"}},
	{"axv",(MIMEtype){"video","annodex"}},
	{"bac",(MIMEtype){"text","x-bacon"}},
	{"bak",(MIMEtype){"application","x-trash"}},
	{"bas",(MIMEtype){"text","plain"}},
	{"bcpio",(MIMEtype){"application","x-bcpio"}},
	{"bdf",(MIMEtype){"application","x-font-bdf"}},
	{"bfe",(MIMEtype){"application","x-bfe"}},
	{"bib",(MIMEtype){"text","x-bibtex"}},
	{"bin",(MIMEtype){"application","octet-stream"}},
	{"blend",(MIMEtype){"application","x-blender"}},
	{"blender",(MIMEtype){"application","x-blender"}},
	{"bmp",(MIMEtype){"image","bmp"}},
	{"btrfs",(MIMEtype){"application","x-btrfs-image"}},
	{"bz",(MIMEtype){"application","x-bzip"}},
	{"bz2",(MIMEtype){"application","x-bzip"}},
	{"c",(MIMEtype){"text","x-csrc"}},
	{"c++",(MIMEtype){"text","x-c++src"}},
	{"cab",(MIMEtype){"application","vnd.ms-cab-compressed"}},
	{"cat",(MIMEtype){"application","vnd.ms-pkiseccat"}},
	{"cb7",(MIMEtype){"application","x-cb7"}},
	{"cbr",(MIMEtype){"application","x-cbr"}},
	{"cbt",(MIMEtype){"application","x-cbt"}},
	{"cbz",(MIMEtype){"application","x-cbz"}},
	{"cc",(MIMEtype){"text","x-c++src"}},
	{"cdf",(MIMEtype){"application","x-netcdf"}},
	{"cdr",(MIMEtype){"application","vnd.corel-draw"}},
	{"cer",(MIMEtype){"application","x-x509-ca-cert"}},
	{"cert",(MIMEtype){"application","x-x509-ca-cert"}},
	{"cgm",(MIMEtype){"image","cgm"}},
	{"changelog",(MIMEtype){"text","x-changelog:ChangeLog"}},
	{"chm",(MIMEtype){"application","x-chm"}},
	{"chrt",(MIMEtype){"application","x-kchart"}},
	{"class",(MIMEtype){"application","x-java"}},
	{"clp",(MIMEtype){"application","x-msclip"}},
	{"cls",(MIMEtype){"text","x-tex"}},
	{"cmakelists.txt",(MIMEtype){"text","x-cmake"}},
	{"cmake",(MIMEtype){"text","x-cmake"}},
	{"cmx",(MIMEtype){"image","x-cmx"}},
	{"cod",(MIMEtype){"image","cis-cod"}},
	{"copying",(MIMEtype){"text","x-copying"}},
	{"cpio",(MIMEtype){"application","x-cpio"}},
	{"cpio.gz",(MIMEtype){"application","x-cpio-compressed"}},
	{"cpp",(MIMEtype){"text","x-c++src"}},
	{"cpt",(MIMEtype){"application","x-ccrypt"}},
	{"cr2",(MIMEtype){"image","x-canon-cr2"}},
	{"crd",(MIMEtype){"application","x-mscardfile"}},
	{"credits",(MIMEtype){"text","x-authors"}},
	{"crl",(MIMEtype){"application","pkix-crl"}},
	{"crt",(MIMEtype){"application","x-x509-ca-cert"}},
	{"crw",(MIMEtype){"image","x-canon-crw"}},
	{"cs",(MIMEtype){"text","x-csharp"}},
	{"csh",(MIMEtype){"application","x-csh"}},
	{"cssl",(MIMEtype){"text","css"}},
	{"css",(MIMEtype){"text","css"}},
	{"csv",(MIMEtype){"text","csv"}},
	{"cue",(MIMEtype){"application","x-cue"}},
	{"cur",(MIMEtype){"image","x-win-bitmap"}},
	{"cxx",(MIMEtype){"text","x-c++src"}},
	{"d",(MIMEtype){"text","x-dsrc"}},
	{"dar",(MIMEtype){"application","x-dar"}},
	{"dat",(MIMEtype){"video","mpeg"}}, /* doesn't seem right */
	{"dbf",(MIMEtype){"application","x-dbf"}},
	{"dc",(MIMEtype){"application","x-dc-rom"}},
	{"dcl",(MIMEtype){"text","x-dcl"}},
	{"dcm",(MIMEtype){"application","dicom"}},
	{"dcr",(MIMEtype){"image","x-kodak-dcr"}},//{"dcr",(MIMEtype){"application","x-director"}},
	{"dds",(MIMEtype){"image","x-dds"}},
	{"deb",(MIMEtype){"application","x-deb"}},
	{"delta",(MIMEtype){"application","x-delta"}},
	{"der",(MIMEtype){"application","x-x509-ca-cert"}},
	{"desktop",(MIMEtype){"application","x-desktop"}},
	{"dia",(MIMEtype){"application","x-dia-diagram"}},
	{"diff",(MIMEtype){"text","x-patch"}},//{"diff",(MIMEtype){"text","x-diff"}},
	{"dir",(MIMEtype){"application","x-director"}},
	{"divx",(MIMEtype){"video","x-msvideo"}},
	{"djv",(MIMEtype){"image","vnd.djvu"}},
	{"djvu",(MIMEtype){"image","vnd.djvu"}},
	{"dll",(MIMEtype){"application","x-msdownload"}},
	{"dms",(MIMEtype){"application","octet-stream"}},
	{"dng",(MIMEtype){"image","x-adobe-dng"}},
	{"doc",(MIMEtype){"application","msword"}},
	{"docbook",(MIMEtype){"application","docbook+xml"}},
	{"docm",(MIMEtype){"application","vnd.openxmlformats-officedocument.wordprocessingml.document"}},
	{"docx",(MIMEtype){"application","vnd.openxmlformats-officedocument.wordprocessingml.document"}},
	{"dot",(MIMEtype){"application","msword-template"}},
	{"dpatch",(MIMEtype){"text","x-diff"}},
	{"dsl",(MIMEtype){"text","x-dsl"}},
	{"dtd",(MIMEtype){"application","xml-dtd"}},
	{"dtx",(MIMEtype){"text","x-tex"}},
	{"dv",(MIMEtype){"video","dv"}},
	{"dvi",(MIMEtype){"application","x-dvi"}},
	{"dvi.bz2",(MIMEtype){"application","x-bzdvi"}},
	{"dvi.gz",(MIMEtype){"application","x-gzdvi"}},
	{"dwg",(MIMEtype){"image","vnd.dwg"}},
	{"dxf",(MIMEtype){"image","vnd.dxf"}},
	{"dxr",(MIMEtype){"application","x-director"}},
	{"e",(MIMEtype){"text","x-eiffel"}},
	{"edi",(MIMEtype){"application","EDI-X12"}},
	{"egon",(MIMEtype){"application","x-egon"}},
	{"eif",(MIMEtype){"text","x-eiffel"}},
	{"eim",(MIMEtype){"image","x-eim"}},
	{"el",(MIMEtype){"text","x-emacs-lisp"}},
	{"emf",(MIMEtype){"image","x-emf"}},
	{"eml",(MIMEtype){"message","rfc822"}},
	{"emp",(MIMEtype){"application","vnd.emusic-emusic_package"}},
	{"ent",(MIMEtype){"application","xml-external-parsed-entity"}},
	{"eps",(MIMEtype){"image","x-eps"}},
	{"eps.bz2",(MIMEtype){"image","x-bzeps"}},
	{"eps.gz",(MIMEtype){"image","x-gzeps"}},
	{"epsf",(MIMEtype){"image","x-eps"}},
	{"epsf.bz2",(MIMEtype){"image","x-bzeps"}},
	{"epsf.gz",(MIMEtype){"image","x-gzeps"}},
	{"epsi.gz",(MIMEtype){"image","x-gzeps"}},
	{"epsi",(MIMEtype){"image","x-eps"}},
	{"epub",(MIMEtype){"application","epub+zip"}},
	{"erl",(MIMEtype){"text","x-erlang"}},
	{"es",(MIMEtype){"application","ecmascript"}},
	{"etheme",(MIMEtype){"application","x-e-theme"}},
	{"etx",(MIMEtype){"text","x-setext"}},//{"etx","text","setext"}},
	{"evy",(MIMEtype){"application","envoy"}},
	{"exe",(MIMEtype){"application","x-ms-dos-executable"}},
	{"exr",(MIMEtype){"image","x-exr"}},
	{"ez",(MIMEtype){"application","andrew-inset"}},
	{"f",(MIMEtype){"text","x-fortran"}},
	{"f2fs",(MIMEtype){"application","x-f2fs-image"}},
	{"f90",(MIMEtype){"text","x-fortran"}},
	{"f95",(MIMEtype){"text","x-fortran"}},
	{"fb2",(MIMEtype){"application","x-fictionbook+xml"}},
	{"fif",(MIMEtype){"application","fractals"}},
	{"fig",(MIMEtype){"image","x-xfig"}},
	{"fits",(MIMEtype){"image","fits"}},
	{"fl",(MIMEtype){"application","x-fluid"}},
	{"flac",(MIMEtype){"audio","x-flac"}},
	{"flc",(MIMEtype){"video","x-flic"}},
	{"fli",(MIMEtype){"video","x-flic"}},
	{"flr",(MIMEtype){"x-world","x-vrml"}},
	{"flv",(MIMEtype){"video","x-flv"}},
	{"flw",(MIMEtype){"application","x-kivio"}},
	{"fo",(MIMEtype){"text","x-xslfo"}},
	{"fodb",(MIMEtype){"application","vnd.oasis.opendocument.database"}},
	{"fodc",(MIMEtype){"application","vnd.oasis.opendocument.chart"}},
	{"fodf",(MIMEtype){"application","vnd.oasis.opendocument.formula"}},
	{"fodg",(MIMEtype){"application","vnd.oasis.opendocument.graphics"}},
	{"fodi",(MIMEtype){"application","vnd.oasis.opendocument.image"}},
	{"fodm",(MIMEtype){"application","vnd.oasis.opendocument.text-master"}},
	{"fodp",(MIMEtype){"application","vnd.oasis.opendocument.presentation"}},
	{"fods",(MIMEtype){"application","vnd.oasis.opendocument.spreadsheet"}},
	{"fodt",(MIMEtype){"application","vnd.oasis.opendocument.text"}},
	{"for",(MIMEtype){"text","x-fortran"}},
	{"g3",(MIMEtype){"image","fax-g3"}},
	{"gb",(MIMEtype){"application","x-gameboy-rom"}},
	{"gba",(MIMEtype){"application","x-gba-rom"}},
	{"gcrd",(MIMEtype){"text","directory"}},
	{"ged",(MIMEtype){"application","x-gedcom"}},
	{"gedcom",(MIMEtype){"application","x-gedcom"}},
	{"gen",(MIMEtype){"application","x-genesis-rom"}},
	{"gf",(MIMEtype){"application","x-tex-gf"}},
	{"gg",(MIMEtype){"application","x-sms-rom"}},
	{"gif",(MIMEtype){"image","gif"}},
	{"glade",(MIMEtype){"application","x-glade"}},
	{"gmo",(MIMEtype){"application","x-gettext-translation"}},
	{"gnc",(MIMEtype){"application","x-gnucash"}},
	{"gnd",(MIMEtype){"application","gnunet-directory"}},
	{"gnucash",(MIMEtype){"application","x-gnucash"}},
	{"gnumeric",(MIMEtype){"application","x-gnumeric"}},
	{"gnuplot",(MIMEtype){"application","x-gnuplot"}},
	{"gp",(MIMEtype){"application","x-gnuplot"}},
	{"gpg",(MIMEtype){"application","pgp-encrypted"}},
	{"gplt",(MIMEtype){"application","x-gnuplot"}},
	{"gra",(MIMEtype){"application","x-graphite"}},
	{"gs",(MIMEtype){"text","x-genie"}},
	{"gsf",(MIMEtype){"application","x-font-type1"}},
	{"gsm",(MIMEtype){"audio","x-gsm"}},
	{"gtar",(MIMEtype){"application","x-tar"}},
	{"gtkrc",(MIMEtype){"text","x-gtkrc"}},
	{"gv",(MIMEtype){"text","vnd.graphviz"}},
	{"gvp",(MIMEtype){"text","x-google-video-pointer"}},
	{"gz",(MIMEtype){"application","gzip"}},
	{"h",(MIMEtype){"text","x-chdr"}},
	{"h++",(MIMEtype){"text","x-c++hdr"}},
	{"hdf",(MIMEtype){"application","x-hdf"}},
	{"hh",(MIMEtype){"text","x-c++hdr"}},
	{"hp",(MIMEtype){"text","x-c++hdr"}},
	{"hlp",(MIMEtype){"application","winhlp"}},
	{"hpgl",(MIMEtype){"application","vnd.hp-hpgl"}},
	{"hpp",(MIMEtype){"text","x-c++hdr"}},
	{"hqx",(MIMEtype){"application","mac-binhex40"}},
	{"hs",(MIMEtype){"text","x-haskell"}},
	{"hta",(MIMEtype){"application","hta"}},
	{"htc",(MIMEtype){"text","x-component"}},
	{"html",(MIMEtype){"text","html"}},
	{"htm",(MIMEtype){"text","html"}},
	{"htt",(MIMEtype){"text","webviewhtml"}},
	{"hwp",(MIMEtype){"application","x-hwp"}},
	{"hwt",(MIMEtype){"application","x-hwt"}},
	{"hxx",(MIMEtype){"text","x-c++hdr"}},
	{"ica",(MIMEtype){"application","x-ica"}},
	{"icb",(MIMEtype){"image","x-tga"}},
	{"icns",(MIMEtype){"image","x-icns"}},
	{"ico",(MIMEtype){"image","vnd.microsoft.icon"}},
	{"ics",(MIMEtype){"text","calendar"}},
	{"idl",(MIMEtype){"text","x-idl"}},
	{"ief",(MIMEtype){"image","ief"}},
	{"iff",(MIMEtype){"image","x-iff"}},
	{"iii",(MIMEtype){"application","x-iphone"}},
	{"ilbm",(MIMEtype){"image","x-ilbm"}},
	{"ime",(MIMEtype){"text","x-iMelody"}},
	{"imy",(MIMEtype){"text","x-iMelody"}},
	{"install",(MIMEtype){"text","x-install"}},
	{"ins",(MIMEtype){"text","x-tex"}},
	{"iptables",(MIMEtype){"text","x-iptables"}},
	{"iso",(MIMEtype){"application","x-cd-image"}},
	{"iso9660",(MIMEtype){"application","x-cd-image"}},
	{"isp",(MIMEtype){"application","x-internet-signup"}},
	{"it",(MIMEtype){"audio","x-it"}},
	{"itz",(MIMEtype){"audio","x-zipped-it"}},
	{"j2k",(MIMEtype){"image","jp2"}},
	{"jad",(MIMEtype){"text","vnd.sun.j2me.app-descriptor"}},
	{"jar",(MIMEtype){"application","x-java-archive"}},
	{"java",(MIMEtype){"text","x-java"}},
	{"jfif",(MIMEtype){"image","pipeg"}},
	{"jng",(MIMEtype){"image","x-jng"}},
	{"jnlp",(MIMEtype){"application","x-java-jnlp-file"}},
	{"jp2",(MIMEtype){"image","jp2"}},
	{"jpc",(MIMEtype){"image","jp2"}},
	{"jpe",(MIMEtype){"image","jpeg"}},
	{"jpeg",(MIMEtype){"image","jpeg"}},
	{"jpf",(MIMEtype){"image","jp2"}},
	{"jpg",(MIMEtype){"image","jpeg"}},
	{"jpr",(MIMEtype){"application","x-jbuilder-project"}},
	{"jpx",(MIMEtype){"image","jp2"}},//{"jpx","application","x-jbuilder-project"}},
	{"js",(MIMEtype){"application","javascript"}},
	{"json",(MIMEtype){"application","json"}},
	{"k25",(MIMEtype){"image","x-kodak-k25"}},
	{"kar",(MIMEtype){"audio","midi"}},
	{"karbon",(MIMEtype){"application","x-karbon"}},
	{"kdc",(MIMEtype){"image","x-kodak-kdc"}},
	{"kdelnk",(MIMEtype){"application","x-desktop"}},
	{"kexi",(MIMEtype){"application","x-kexiproject-sqlite3"}},//{"kexi","application","x-kexiproject-sqlite2"}},
	{"kexic",(MIMEtype){"application","x-kexi-connectiondata"}},
	{"kexis",(MIMEtype){"application","x-kexiproject-shortcut"}},
	{"kfo",(MIMEtype){"application","x-kformula"}},
	{"kil",(MIMEtype){"application","x-killustrator"}},
	{"kino",(MIMEtype){"application","smil"}},
	{"kml",(MIMEtype){"application","vnd.google-earth.kml+xml"}},
	{"kmz",(MIMEtype){"application","vnd.google-earth.kmz"}},
	{"kon",(MIMEtype){"application","x-kontour"}},
	{"kpm",(MIMEtype){"application","x-kpovmodeler"}},
	{"kpr",(MIMEtype){"application","x-kpresenter"}},
	{"kpt",(MIMEtype){"application","x-kpresenter"}},
	{"kra",(MIMEtype){"application","x-krita"}},
	{"ksp",(MIMEtype){"application","x-kspread"}},
	{"kud",(MIMEtype){"application","x-kugar"}},
	{"kwd",(MIMEtype){"application","x-kword"}},
	{"kwt",(MIMEtype){"application","x-kword"}},
	{"la",(MIMEtype){"application","x-shared-library-la"}},
	{"latex",(MIMEtype){"text","x-tex"}},//	{"latex","application","x-latex"}},
	{"ldif",(MIMEtype){"text","x-ldif"}},
	{"lha",(MIMEtype){"application","x-lha"}},
	{"lhs",(MIMEtype){"text","x-literate-haskell"}},
	{"lhz",(MIMEtype){"application","x-lhz"}},
	{"license",(MIMEtype){"text","x-copying"}},
	{"log",(MIMEtype){"text","x-log"}},
	{"lsf",(MIMEtype){"video","x-la-asf"}},
	{"lsx",(MIMEtype){"video","x-la-asf"}},
	{"ltx",(MIMEtype){"text","x-tex"}},
	{"lua",(MIMEtype){"text","x-lua"}},
	{"lwo",(MIMEtype){"image","x-lwo"}},
	{"lwob",(MIMEtype){"image","x-lwo"}},
	{"lws",(MIMEtype){"image","x-lws"}},
	{"ly",(MIMEtype){"text","x-lilypond"}},
	{"lyx",(MIMEtype){"application","x-lyx"}},
	{"lz",(MIMEtype){"application","x-lzip"}},
	{"lzh",(MIMEtype){"application","x-lha"}},
	{"lzma",(MIMEtype){"application","x-lzma"}},
	{"lzo",(MIMEtype){"application","x-lzop"}},
	{"m",(MIMEtype){"text","x-objcsrc"}},
	{"m13",(MIMEtype){"application","x-msmediaview"}},
	{"m14",(MIMEtype){"application","x-msmediaview"}},
	{"m15",(MIMEtype){"audio","x-mod"}},
	{"m2t",(MIMEtype){"video","mpeg"}},
	{"m3u",(MIMEtype){"audio","x-mpegurl"}},
	{"m3u8",(MIMEtype){"audio","x-mpegurl"}},
	{"m4",(MIMEtype){"application","x-m4"}},
	{"m4a",(MIMEtype){"audio","mp4"}},
	{"m4b",(MIMEtype){"audio","x-m4b"}},
	{"m4v",(MIMEtype){"video","mp4"}},
	{"mab",(MIMEtype){"application","x-markaby"}},
	{"makefile",(MIMEtype){"text","x-makefile"}},
	{"man",(MIMEtype){"application","x-troff-man"}},
	{"mbox",(MIMEtype){"application","mbox"}},
	{"md",(MIMEtype){"application","x-genesis-rom"}},
	{"mdb",(MIMEtype){"application","vnd.ms-access"}},//{"mdb","application","x-msaccess"}},
	{"mdi",(MIMEtype){"image","vnd.ms-modi"}},
	{"mdz",(MIMEtype){"audio","x-zipped-mod"}},
	{"med",(MIMEtype){"audio","x-mod"}},
	{"meta4",(MIMEtype){"application","metalink4+xml"}},
	{"metalink",(MIMEtype){"application","metalink+xml"}},
	{"me",(MIMEtype){"text","x-troff-me"}},
	{"mgp",(MIMEtype){"application","x-magicpoint"}},
	{"mhtml",(MIMEtype){"multipart","related"}}, /* message","rfc822 */
	{"mht",(MIMEtype){"multipart","related"}}, /* message","rfc822 */
	{"mid",(MIMEtype){"audio","midi"}},
	{"midi",(MIMEtype){"audio","midi"}},
	{"mif",(MIMEtype){"application","x-mif"}},
	{"minipsf",(MIMEtype){"audio","x-minipsf"}},
	{"mk3d",(MIMEtype){"video","x-matroska"}},
	{"mka",(MIMEtype){"audio","x-matroska"}},
	{"mkv",(MIMEtype){"video","x-matroska"}},
	{"ml",(MIMEtype){"text","x-ocaml"}},
	{"mli",(MIMEtype){"text","x-ocaml"}},
	{"mm",(MIMEtype){"text","x-troff-mm"}},
	{"mmf",(MIMEtype){"application","x-smaf"}},
	{"mml",(MIMEtype){"application","mathml+xml"}},//{"mml",(MIMEtype){"text","mathml"}},
	{"mng",(MIMEtype){"video","x-mng"}},
	{"mny",(MIMEtype){"application","x-msmoney"}},
	{"mo",(MIMEtype){"application","x-gettext-translation"}},
	{"mo3",(MIMEtype){"audio","x-mo3"}},
	{"moc",(MIMEtype){"text","x-moc"}},
	{"mod",(MIMEtype){"audio","x-mod"}},
	{"mof",(MIMEtype){"text","x-mof"}},
	{"moov",(MIMEtype){"video","quicktime"}},
	{"mov",(MIMEtype){"video","quicktime"}},
	{"movie",(MIMEtype){"video","x-sgi-movie"}},
	{"mp+",(MIMEtype){"audio","x-musepack"}},
	{"mp2",(MIMEtype){"video","mpeg"}},//{"mp2",(MIMEtype){"audio","mp2"}},
	{"mp3",(MIMEtype){"audio","mp3"}},//{"mp3",(MIMEtype){"audio","mpeg"}},
	{"mp4",(MIMEtype){"video","mp4"}},//{"mp4",(MIMEtype){"video","mpeg},
	{"mpc",(MIMEtype){"audio","x-musepack"}},
	{"mpeg",(MIMEtype){"video","mpeg"}},
	{"mpe",(MIMEtype){"video","mpeg"}},
	{"mpga",(MIMEtype){"audio","mpeg"}},
	{"mpg",(MIMEtype){"video","mpeg"}},
	{"mpp",(MIMEtype){"application","vnd.ms-project"}},//{"mpp",(MIMEtype){"audio","x-musepack"}},
	{"mpv2",(MIMEtype){"video","mpeg"}},
	{"mrl",(MIMEtype){"text","x-mrml"}},
	{"mrml",(MIMEtype){"text","x-mrml"}},
	{"mrw",(MIMEtype){"image","x-minolta-mrw"}},
	{"ms",(MIMEtype){"text","x-troff-ms"}},
	{"msg",(MIMEtype){"application","vnd.ms-outlook"}},
	{"msi",(MIMEtype){"application","x-msi"}},
	{"msod",(MIMEtype){"image","x-msod"}},
	{"msx",(MIMEtype){"application","x-msx-rom"}},
	{"mtm",(MIMEtype){"audio","x-mod"}},
	{"mup",(MIMEtype){"text","x-mup"}},
	{"mvb",(MIMEtype){"application","x-ms-mediaview"}},
	{"mxf",(MIMEtype){"application","mxf"}},
	{"n64",(MIMEtype){"application","x-n64-rom"}},
	{"nb",(MIMEtype){"application","mathematica"}},
	{"nc",(MIMEtype){"application","x-netcdf"}},
	{"ncd",(MIMEtype){"application","notecase-plain"}},
	{"nce",(MIMEtype){"application","notecase-enc"}},
	{"nds",(MIMEtype){"application","x-nintendo-ds-rom"}},
	{"nef",(MIMEtype){"image","x-nikon-nef"}},
	{"nes",(MIMEtype){"application","x-nes-rom"}},
	{"nfo",(MIMEtype){"text","x-nfo"}},
	{"not",(MIMEtype){"text","x-mup"}},
	{"nsc",(MIMEtype){"application","x-netshow-channel"}},
	{"nsv",(MIMEtype){"video","x-nsv"}},
	{"nws",(MIMEtype){"message","rfc822"}},
	{"o",(MIMEtype){"application","x-object"}},
	{"obj",(MIMEtype){"application","x-tgif"}},
	{"ocl",(MIMEtype){"text","x-ocl"}},
	{"oda",(MIMEtype){"application","oda"}},
	{"odb",(MIMEtype){"application","vnd.oasis.opendocument.database"}},
	{"odc",(MIMEtype){"application","vnd.oasis.opendocument.chart"}},
	{"odf",(MIMEtype){"application","vnd.oasis.opendocument.formula"}},
	{"odg",(MIMEtype){"application","vnd.oasis.opendocument.graphics"}},
	{"odi",(MIMEtype){"application","vnd.oasis.opendocument.image"}},
	{"odm",(MIMEtype){"application","vnd.oasis.opendocument.text-master"}},
	{"odp",(MIMEtype){"application","vnd.oasis.opendocument.presentation"}},
	{"ods",(MIMEtype){"application","vnd.oasis.opendocument.spreadsheet"}},
	{"odt",(MIMEtype){"application","vnd.oasis.opendocument.text"}},
	{"oga",(MIMEtype){"audio","ogg"}},
	{"ogg",(MIMEtype){"application","ogg"}},//{"ogg",(MIMEtype){"audio","ogg"}},//{"ogg",(MIMEtype){"audio","x-flac+ogg"}},//{"ogg",(MIMEtype){"audio","x-speex+ogg"}},//{"ogg",(MIMEtype){"audio","x-vorbis+ogg"}},//{"ogg",(MIMEtype){"video","x-theora+ogg"}},
	{"ogm",(MIMEtype){"video","x-ogm+ogg"}},
	{"ogv",(MIMEtype){"video","ogg"}},
	{"ogx",(MIMEtype){"application","ogg"}},
	{"old",(MIMEtype){"application","x-trash"}},
	{"oleo",(MIMEtype){"application","x-oleo"}},
	{"opml",(MIMEtype){"text","x-opml+xml"}},
	{"ora",(MIMEtype){"image","openraster"}},
	{"orf",(MIMEtype){"image","x-olympus-orf"}},
	{"otb",(MIMEtype){"application","vnd.oasis.opendocument.database-template"}},
	{"otc",(MIMEtype){"application","vnd.oasis.opendocument.chart-template"}},
	{"otf",(MIMEtype){"application","vnd.oasis.opendocument.formula-template"}}, //{"otf",(MIMEtype){"application","x-font-otf"}},
	{"otg",(MIMEtype){"application","vnd.oasis.opendocument.graphics-template"}},
	{"oth",(MIMEtype){"application","vnd.oasis.opendocument.text-web"}},
	{"oti",(MIMEtype){"application","vnd.oasis.opendocument.image-template"}},
	{"otm",(MIMEtype){"application","vnd.oasis.opendocument.text-master-template"}},
	{"otp",(MIMEtype){"application","vnd.oasis.opendocument.presentation-template"}},
	{"ots",(MIMEtype){"application","vnd.oasis.opendocument.spreadsheet-template"}},
	{"ott",(MIMEtype){"application","vnd.oasis.opendocument.text-template"}},
	{"owl",(MIMEtype){"application","rdf+xml"}},
	{"oxt",(MIMEtype){"application","vnd.openofficeorg.extension"}},
	{"p",(MIMEtype){"text","x-pascal"}},
	{"p10",(MIMEtype){"application","pkcs10"}},
	{"p12",(MIMEtype){"application","x-pkcs12"}},
	{"p7b",(MIMEtype){"application","x-pkcs7-certificates"}},
	{"p7c",(MIMEtype){"application","x-pkcs7-mime"}},
	{"p7r",(MIMEtype){"application","x-pkcs7-certreqresp"}},
	{"p7s",(MIMEtype){"application","pkcs7-signature"}},//{"p7s",(MIMEtype){"application","x-pkcs7-signature"}},
	{"pack",(MIMEtype){"application","x-java-pack200"}},//{"pack",(MIMEtype){"application","x-windows-themepack"}},
	{"pak",(MIMEtype){"application","x-pak"}},
	{"par2",(MIMEtype){"application","x-par2"}},
	{"pas",(MIMEtype){"text","x-pascal"}},
	{"patch",(MIMEtype){"text","x-patch"}},//	{"patch",(MIMEtype){"text","x-diff"}},
	{"pbm",(MIMEtype){"image","x-portable-bitmap"}},
	{"pcd",(MIMEtype){"image","x-photo-cd"}},
	{"pcf",(MIMEtype){"application","x-font-pcf"}},//{"pcf",(MIMEtype){"application","x-cisco-vpn-settings"}},
	{"pcf.gz",(MIMEtype){"application","x-font-pcf"}},
	{"pcf.z",(MIMEtype){"application","x-font-pcf"}},
	{"pcl",(MIMEtype){"application","vnd.hp-pcl"}},
	{"pcx",(MIMEtype){"image","x-pcx"}},
	{"pdb",(MIMEtype){"application","x-palm-database"}},//{"pdb",(MIMEtype){"application","x-aportisdoc"}},
	{"pdc",(MIMEtype){"application","x-aportisdoc"}},
	{"pdf",(MIMEtype){"application","pdf"}},
	{"pdf.bz2",(MIMEtype){"application","x-bzpdf"}},
	{"pdf.gz",(MIMEtype){"application","x-gzpdf"}},
	{"pef",(MIMEtype){"image","x-pentax-pef"}},
	{"pem",(MIMEtype){"application","x-x509-ca-cert"}},
	{"perl",(MIMEtype){"application","x-perl"}},//{"perl",(MIMEtype){"text","x-perl"}},
	{"pet",(MIMEtype){"application","pet"}},
	{"pfa",(MIMEtype){"application","x-font-type1"}},
	{"pfb",(MIMEtype){"application","x-font-type1"}},
	{"pfx",(MIMEtype){"application","x-pkcs12"}},
	{"pgm",(MIMEtype){"image","x-portable-graymap"}},
	{"pgn",(MIMEtype){"application","x-chess-pgn"}},
	{"pgp",(MIMEtype){"application","pgp-encrypted"}},
	{"php",(MIMEtype){"application","x-php"}},
	{"php3",(MIMEtype){"application","x-php"}},
	{"pict",(MIMEtype){"image","x-pict"}},
	{"pict1",(MIMEtype){"image","x-pict"}},
	{"pict2",(MIMEtype){"image","x-pict"}},
	{"pk",(MIMEtype){"application","x-tex-pk"}},
	{"pkg.tar.gz",(MIMEtype){"application","x-pkg"}},
	{"pkipath",(MIMEtype){"application","pkix-pkipath"}},
	{"pko",(MIMEtype){"application","vnd.ms-pkipko"}},
	{"pkr",(MIMEtype){"application","pgp-keys"}},
	{"pl",(MIMEtype){"application","x-perl"}},
	{"pla",(MIMEtype){"audio","x-iriver-pla"}},
	{"pln",(MIMEtype){"application","x-planperfect"}},
	{"pls",(MIMEtype){"audio","x-scpls"}},
	{"pm",(MIMEtype){"application","x-perl"}},
	{"pma",(MIMEtype){"application","x-perfmon"}},
	{"pmc",(MIMEtype){"application","x-perfmon"}},
	{"pml",(MIMEtype){"application","x-perfmon"}},
	{"pmr",(MIMEtype){"application","x-perfmon"}},
	{"pmw",(MIMEtype){"application","x-perfmon"}},
	{"png",(MIMEtype){"image","png"}},
	{"pnm",(MIMEtype){"image","x-portable-anymap"}},
	{"pntg",(MIMEtype){"image","x-macpaint"}},
	{"po",(MIMEtype){"text","x-gettext-translation"}},
	{"por",(MIMEtype){"application","x-spss-por"}},
	{"pot",(MIMEtype){"text","x-gettext-translation-template"}},//{"pot",(MIMEtype){"application","vnd.ms-powerpoint"}},
	{"pov",(MIMEtype){"text","x-povray"}},
	{"ppm",(MIMEtype){"image","x-portable-pixmap"}},
	{"pps",(MIMEtype){"application","vnd.ms-powerpoint"}},
	{"ppsm",(MIMEtype){"application","vnd.openxmlformats-officedocument.presentationml.presentation"}},
	{"ppsx",(MIMEtype){"application","vnd.openxmlformats-officedocument.presentationml.presentation"}},
	{"ppt",(MIMEtype){"application","vnd.ms-powerpoint"}},
	{"pptm",(MIMEtype){"application","vnd.openxmlformats-officedocument.presentationml.presentation"}},
	{"pptx",(MIMEtype){"application","vnd.openxmlformats-officedocument.presentationml.presentation"}},
	{"ppz",(MIMEtype){"application","vnd.ms-powerpoint"}},
	{"prc",(MIMEtype){"application","x-palm-database"}},
	{"prf",(MIMEtype){"application","pics-rules"}},
	{"ps",(MIMEtype){"application","postscript"}},
	{"ps.bz2",(MIMEtype){"application","x-bzpostscript"}},
	{"ps.gz",(MIMEtype){"application","x-gzpostscript"}},
	{"psd",(MIMEtype){"image","vnd.adobe.photoshop"}},//{"psd",(MIMEtype){"image","x-psd"}},
	{"psf",(MIMEtype){"application","x-font-linux-psf"}},//{"psf",(MIMEtype){"audio","x-psf"}},
	{"psf.gz",(MIMEtype){"application","x-gz-font-linux-psf"}},
	{"psflib",(MIMEtype){"audio","x-psflib"}},
	{"psid",(MIMEtype){"audio","prs.sid"}},
	{"psw",(MIMEtype){"application","x-pocket-word"}},
	{"pub",(MIMEtype){"application","x-mspublisher"}},
	{"pup",(MIMEtype){"application","pup"}},
	{"pw",(MIMEtype){"application","x-pw"}},
	{"py",(MIMEtype){"text","x-python"}},
	{"pyc",(MIMEtype){"application","x-python-bytecode"}},
	{"pyo",(MIMEtype){"application","x-python-bytecode"}},
	{"qif",(MIMEtype){"application","x-qw"}},//{"qif",(MIMEtype){"image","x-quicktime"}},
	{"qt",(MIMEtype){"video","quicktime"}},
	{"qtif",(MIMEtype){"image","x-quicktime"}},
	{"qtl",(MIMEtype){"application","x-quicktime-media-link"}},
	{"qtvr",(MIMEtype){"video","quicktime"}},
	{"ra",(MIMEtype){"audio","vnd.rn-realaudio"}},
	{"raf",(MIMEtype){"image","x-fuji-raf"}},
	{"ram",(MIMEtype){"application","ram"}},//{"ram",(MIMEtype){"audio","x-pn-realaudio"}},
	{"rar",(MIMEtype){"application","x-rar"}},//{"rar",(MIMEtype){"application","x-rar-compressed"}},
	{"ras",(MIMEtype){"image","x-cmu-raster"}},
	{"raw",(MIMEtype){"image","x-panasonic-raw"}},
	{"rax",(MIMEtype){"audio","vnd.rn-realaudio"}},
	{"rb",(MIMEtype){"application","x-ruby"}},
	{"rdf",(MIMEtype){"application","rdf+xml"}},
	{"rdfs",(MIMEtype){"application","rdf+xml"}},
	{"readme",(MIMEtype){"text","x-readme"}},
	{"reg",(MIMEtype){"text","x-ms-regedit"}},
	{"rej",(MIMEtype){"application","x-reject"}},
	{"rgb",(MIMEtype){"image","x-rgb"}},
	{"rle",(MIMEtype){"image","rle"}},
	{"rm",(MIMEtype){"application","vnd.rn-realmedia"}},
	{"rmi",(MIMEtype){"audio","mid"}},
	{"rmj",(MIMEtype){"application","vnd.rn-realmedia"}},
	{"rmm",(MIMEtype){"application","vnd.rn-realmedia"}},
	{"rms",(MIMEtype){"application","vnd.rn-realmedia"}},
	{"rmvb",(MIMEtype){"application","vnd.rn-realmedia"}},
	{"rmx",(MIMEtype){"application","vnd.rn-realmedia"}},
	{"roff",(MIMEtype){"text","troff"}},//{"roff",(MIMEtype){"text","x-troff"}},
	{"rp",(MIMEtype){"image","vnd.rn-realpix"}},
	{"rpm",(MIMEtype){"application","x-rpm"}},
	{"rss",(MIMEtype){"application","rss+xml"}},
	{"rt",(MIMEtype){"text","vnd.rn-realtext"}},
	{"rtf",(MIMEtype){"application","rtf"}},
	{"rtx",(MIMEtype){"text","richtext"}},
	{"rv",(MIMEtype){"video","vnd.rn-realvideo"}},
	{"rvx",(MIMEtype){"video","vnd.rn-realvideo"}},
	{"s",(MIMEtype){"text","plain"}},
	{"s3m",(MIMEtype){"audio","x-s3m"}},
	{"sam",(MIMEtype){"application","x-amipro"}},
	{"sami",(MIMEtype){"application","x-sami"}},
	{"sav",(MIMEtype){"application","x-spss-sav"}},
	{"scd",(MIMEtype){"application","x-msschedule"}},
	{"scm",(MIMEtype){"text","x-scheme"}},
	{"sct",(MIMEtype){"text","scriptlet"}},
	{"sda",(MIMEtype){"application","vnd.stardivision.draw"}},
	{"sdc",(MIMEtype){"application","vnd.stardivision.calc"}},
	{"sdd",(MIMEtype){"application","vnd.stardivision.impress"}},
	{"sdp",(MIMEtype){"application","vnd.stardivision.impress"}},//{"sdp",(MIMEtype){"application","sdp"}},
	{"sds",(MIMEtype){"application","vnd.stardivision.chart"}},
	{"sdw",(MIMEtype){"application","vnd.stardivision.writer"}},
	{"sfs",(MIMEtype){"application","x-squashfs-image"}},
	{"sgf",(MIMEtype){"application","x-go-sgf"}},
	{"sgi",(MIMEtype){"image","x-sgi"}},
	{"sgl",(MIMEtype){"application","vnd.stardivision.writer"}},
	{"sgm",(MIMEtype){"text","sgml"}},
	{"sgml",(MIMEtype){"text","sgml"}},
	{"sh",(MIMEtype){"application","x-shellscript"}},
	{"shar",(MIMEtype){"application","x-shar"}},
	{"shn",(MIMEtype){"application","x-shorten"}},
	{"siag",(MIMEtype){"application","x-siag"}},
	{"sid",(MIMEtype){"audio","prs.sid"}},
	{"sik",(MIMEtype){"application","x-trash"}},
	{"sis",(MIMEtype){"application","vnd.symbian.install"}},
	{"sisx",(MIMEtype){"x-epoc","x-sisx-app"}},
	{"sit",(MIMEtype){"application","x-stuffit"}},
	{"siv",(MIMEtype){"application","sieve"}},
	{"sk",(MIMEtype){"image","x-skencil"}},
	{"sk1",(MIMEtype){"image","x-skencil"}},
	{"skr",(MIMEtype){"application","pgp-keys"}},
	{"slk",(MIMEtype){"text","spreadsheet"}},
	{"smaf",(MIMEtype){"application","x-smaf"}},
	{"smc",(MIMEtype){"application","x-snes-rom"}},
	{"smd",(MIMEtype){"application","vnd.stardivision.mail"}},
	{"smf",(MIMEtype){"application","vnd.stardivision.math"}},
	{"smi",(MIMEtype){"application","smil"}},//{"smi",(MIMEtype){"application","x-sami"}},
	{"smil",(MIMEtype){"application","smil"}},
	{"sml",(MIMEtype){"application","smil"}},
	{"sms",(MIMEtype){"application","x-sms-rom"}},
	{"snd",(MIMEtype){"audio","basic"}},
	{"so",(MIMEtype){"application","x-sharedlib"}},
	{"spc",(MIMEtype){"application","x-pkcs7-certificates"}},
	{"spd",(MIMEtype){"application","x-font-speedo"}},
	{"spec",(MIMEtype){"text","x-rpm-spec"}},
	{"spl",(MIMEtype){"application","x-shockwave-flash"}},
	{"spx",(MIMEtype){"audio","speex"}}, //{"spx",(MIMEtype){"audio","ogg"}},//{"spx",(MIMEtype){"audio","x-speex"}},
	{"sql",(MIMEtype){"text","x-sql"}},
	{"sr2",(MIMEtype){"image","x-sony-sr2"}},
	{"src",(MIMEtype){"application","x-wais-source"}},
	{"srf",(MIMEtype){"image","x-sony-srf"}},
	{"srt",(MIMEtype){"application","x-subrip"}},
	{"ssa",(MIMEtype){"text","x-ssa"}},
	{"stc",(MIMEtype){"application","vnd.sun.xml.calc.template"}},
	{"std",(MIMEtype){"application","vnd.sun.xml.draw.template"}},
	{"sti",(MIMEtype){"application","vnd.sun.xml.impress.template"}},
	{"stm",(MIMEtype){"audio","x-stm"}},
	{"stw",(MIMEtype){"application","vnd.sun.xml.writer.template"}},
	{"sty",(MIMEtype){"text","x-tex"}},
	{"sub",(MIMEtype){"text","x-microdvd"}},//{"sub",(MIMEtype){"text","x-mpsub"}},//{"sub",(MIMEtype){"text","x-subviewer"}},
	{"sun",(MIMEtype){"image","x-sun-raster"}},
	{"sv4cpio",(MIMEtype){"application","x-sv4cpio"}},	
	{"sv4crc",(MIMEtype){"application","x-sv4crc"}},
	{"svg",(MIMEtype){"image","svg+xml"}},
	{"svgz",(MIMEtype){"image","svg+xml-compressed"}},
	{"swf",(MIMEtype){"application","x-shockwave-flash"}},
	{"sxc",(MIMEtype){"application","vnd.sun.xml.calc"}},
	{"sxd",(MIMEtype){"application","vnd.sun.xml.draw"}},
	{"sxg",(MIMEtype){"application","vnd.sun.xml.writer.global"}},
	{"sxi",(MIMEtype){"application","vnd.sun.xml.impress"}},
	{"sxm",(MIMEtype){"application","vnd.sun.xml.math"}},
	{"sxw",(MIMEtype){"application","vnd.sun.xml.writer"}},
	{"sylk",(MIMEtype){"text","spreadsheet"}},
	{"t",(MIMEtype){"text","troff"}},
	{"t2t",(MIMEtype){"text","x-txt2tags"}},
	{"taf",(MIMEtype){"application","x-adrift"}},
	{"tar",(MIMEtype){"application","x-tar"}},
	{"tar.bz",(MIMEtype){"application","x-bzip-compressed-tar"}},
	{"tar.bz2",(MIMEtype){"application","x-bzip-compressed-tar"}},
	{"tar.gz",(MIMEtype){"application","x-compressed-tar"}},
	{"tar.lzma",(MIMEtype){"application","x-lzma-compressed-tar"}},
	{"tar.lzo",(MIMEtype){"application","x-tzo"}},
	{"tar.xz",(MIMEtype){"application","x-xz-compressed-tar"}},
	{"tar.z",(MIMEtype){"application","x-tarz"}},
	{"tbz",(MIMEtype){"application","x-bzip-compressed-tar"}},
	{"tbz2",(MIMEtype){"application","x-bzip-compressed-tar"}},
	{"tcl",(MIMEtype){"text","x-tcl"}},
	{"tex",(MIMEtype){"text","x-tex"}},//{"tex",(MIMEtype){"application","x-latex"}},
	{"texi",(MIMEtype){"text","x-texinfo"}},
	{"texinfo",(MIMEtype){"text","x-texinfo"}},
	{"tga",(MIMEtype){"image","x-tga"}},
	{"tgz",(MIMEtype){"application","x-compressed-tar"}},
	{"theme",(MIMEtype){"application","x-theme"}},
	{"themepack",(MIMEtype){"application","x-windows-themepack"}},
	{"tif",(MIMEtype){"image","tiff"}},
	{"tiff",(MIMEtype){"image","tiff"}},
	{"tk",(MIMEtype){"text","x-tcl"}},
	{"tlz",(MIMEtype){"application","x-lzma-compressed-tar"}},
	{"tnef",(MIMEtype){"application","vnd.ms-tnef"}},
	{"tnf",(MIMEtype){"application","vnd.ms-tnef"}},
	{"toc",(MIMEtype){"application","x-cdrdao-toc"}},
	{"torrent",(MIMEtype){"application","x-bittorrent"}},
	{"tpic",(MIMEtype){"image","x-tga"}},
	{"tr",(MIMEtype){"text","troff"}},
	{"ts",(MIMEtype){"application","x-linguist"}},
	{"tsv",(MIMEtype){"text","tab-separated-values"}},
	{"tta",(MIMEtype){"audio","x-tta"}},
	{"ttc",(MIMEtype){"application","x-font-ttf"}},
	{"ttf",(MIMEtype){"application","x-font-ttf"}},
	{"ttx",(MIMEtype){"application","x-font-ttx"}},
	{"txt",(MIMEtype){"text","plain"}},
	{"txz",(MIMEtype){"application","x-xz-compressed-tar"}},
	{"tzo",(MIMEtype){"application","x-tzo"}},
	{"ufraw",(MIMEtype){"application","x-ufraw"}},
	{"ui",(MIMEtype){"application","x-designer"}},
	{"uil",(MIMEtype){"text","x-uil"}},
	{"ult",(MIMEtype){"audio","x-mod"}},
	{"uni",(MIMEtype){"audio","x-mod"}},
	{"uri",(MIMEtype){"text","x-uri"}},
	{"url",(MIMEtype){"text","x-uri"}},
	{"ustar",(MIMEtype){"application","x-ustar"}},
	{"vala",(MIMEtype){"text","x-vala"}},
	{"vapi",(MIMEtype){"text","x-vala"}},
	{"vcard",(MIMEtype){"text","vcard"}},
	{"vcf",(MIMEtype){"text","directory"}},//{"vcf",(MIMEtype){"text","vcard"}},
	{"vcs",(MIMEtype){"text","calendar"}},
	{"vct",(MIMEtype){"text","directory"}},
	{"vda",(MIMEtype){"image","x-tga"}},
	{"vhd",(MIMEtype){"text","x-vhdl"}},
	{"vhdl",(MIMEtype){"text","x-vhdl"}},
	{"vide",(MIMEtype){"application","x-vide"}},
	{"viv",(MIMEtype){"video","vivo"}},
	{"vivo",(MIMEtype){"video","vivo"}},
	{"vlc",(MIMEtype){"audio","x-mpegurl"}},
	{"vob",(MIMEtype){"video","mpeg"}},
	{"voc",(MIMEtype){"audio","x-voc"}},
	{"vor",(MIMEtype){"application","vnd.stardivision.writer"}},
	{"vst",(MIMEtype){"image","x-tga"}},
	{"wav",(MIMEtype){"audio","x-wav"}},//{"wav",(MIMEtype){"audio","wav"}},
	{"wax",(MIMEtype){"audio","x-ms-asx"}},
	{"wb1",(MIMEtype){"application","x-quattropro"}},
	{"wb2",(MIMEtype){"application","x-quattropro"}},
	{"wb3",(MIMEtype){"application","x-quattropro"}},
	{"wbmp",(MIMEtype){"image","vnd.wap.wbmp"}},
	{"wcm",(MIMEtype){"application","vnd.ms-works"}},
	{"wdb",(MIMEtype){"application","vnd.ms-works"}},
	{"webm",(MIMEtype){"video","webm"}},
	{"wk1",(MIMEtype){"application","vnd.lotus-1-2-3"}},
	{"wk3",(MIMEtype){"application","vnd.lotus-1-2-3"}},
	{"wk4",(MIMEtype){"application","vnd.lotus-1-2-3"}},
	{"wks",(MIMEtype){"application","vnd.ms-works"}},//{"wks",(MIMEtype){"application","vnd.lotus-1-2-3"}},
	{"wma",(MIMEtype){"audio","x-ms-wma"}},
	{"wmf",(MIMEtype){"image","x-wmf"}},
	{"wml",(MIMEtype){"text","vnd.wap.wml"}},
	{"wmls",(MIMEtype){"text","vnd.wap.wmlscript"}},
	{"wmv",(MIMEtype){"video","x-ms-wmv"}},
	{"wmx",(MIMEtype){"audio","x-ms-asx"}},
	{"woff",(MIMEtype){"application","font-woff"}},
	{"wp",(MIMEtype){"application","vnd.wordperfect"}},
	{"wp4",(MIMEtype){"application","vnd.wordperfect"}},
	{"wp5",(MIMEtype){"application","vnd.wordperfect"}},
	{"wp6",(MIMEtype){"application","vnd.wordperfect"}},
	{"wpd",(MIMEtype){"application","vnd.wordperfect"}},
	{"wpg",(MIMEtype){"application","x-wpg"}},
	{"wpl",(MIMEtype){"application","vnd.ms-wpl"}},
	{"wpp",(MIMEtype){"application","vnd.wordperfect"}},
	{"wps",(MIMEtype){"application","vnd.ms-works"}},
	{"wri",(MIMEtype){"application","x-mswrite"}},
	{"wrl",(MIMEtype){"model","vrml"}},
	{"wv",(MIMEtype){"audio","x-wavpack"}},
	{"wvc",(MIMEtype){"audio","x-wavpack-correction"}},
	{"wvp",(MIMEtype){"audio","x-wavpack"}},
	{"wvx",(MIMEtype){"audio","x-ms-asx"}},
	{"wwf",(MIMEtype){"application","x-wwf"}},
	{"x3f",(MIMEtype){"image","x-sigma-x3f"}},
	{"xac",(MIMEtype){"application","x-gnucash"}},
	{"xbel",(MIMEtype){"application","x-xbel"}},
	{"xbl",(MIMEtype){"application","xml"}},
	{"xbm",(MIMEtype){"image","x-xbitmap"}},
	{"xcf",(MIMEtype){"image","x-xcf"}},
	{"xcf.bz2",(MIMEtype){"image","x-compressed-xcf"}},
	{"xcf.gz",(MIMEtype){"image","x-compressed-xcf"}},
	{"xht",(MIMEtype){"application","xhtml+xml"}},
	{"xhtm",(MIMEtype){"application","xhtml+xml"}},
	{"xhtml",(MIMEtype){"application","xhtml+xml"}},
	{"xi",(MIMEtype){"audio","x-xi"}},
	{"xla",(MIMEtype){"application","vnd.ms-excel"}},
	{"xlc",(MIMEtype){"application","vnd.ms-excel"}},
	{"xld",(MIMEtype){"application","vnd.ms-excel"}},
	{"xlf",(MIMEtype){"application","x-xliff"}},
	{"xliff",(MIMEtype){"application","x-xliff"}},
	{"xll",(MIMEtype){"application","vnd.ms-excel"}},
	{"xlm",(MIMEtype){"application","vnd.ms-excel"}},
	{"xls",(MIMEtype){"application","vnd.ms-excel"}},
	{"xlsb",(MIMEtype){"application","vnd.openxmlformats-officedocument.spreadsheetml.sheet"}},
	{"xlsm",(MIMEtype){"application","vnd.openxmlformats-officedocument.spreadsheetml.sheet"}},
	{"xlsx",(MIMEtype){"application","vnd.openxmlformats-officedocument.spreadsheetml.sheet"}},
	{"xlt",(MIMEtype){"application","vnd.ms-excel"}},
	{"xlw",(MIMEtype){"application","vnd.ms-excel"}},
	{"xm",(MIMEtype){"audio","x-xm"}},
	{"xmf",(MIMEtype){"audio","x-xmf"}},
	{"xmi",(MIMEtype){"text","x-xmi"}},
	{"xml",(MIMEtype){"application","xml"}},//{"xml",(MIMEtype){"text","xml"}},
	{"xpm",(MIMEtype){"image","x-xpixmap"}},
	{"xps",(MIMEtype){"application","vnd.ms-xpsdocument"}},
	{"xsl",(MIMEtype){"application","xml"}},
	{"xslfo",(MIMEtype){"text","x-xslfo"}},
	{"xslt",(MIMEtype){"application","xml"}},
	{"xspf",(MIMEtype){"application","xspf+xml"}},
	{"xul",(MIMEtype){"application","vnd.mozilla.xul+xml"}},
	{"xwd",(MIMEtype){"image","x-xwindowdump"}},
	{"xz",(MIMEtype){"application","x-xz"}},
	{"z",(MIMEtype){"application","x-compress"}},
	{"zabw",(MIMEtype){"application","x-abiword"}},
	{"zip",(MIMEtype){"application","zip"}},
	{"zoo",(MIMEtype){"application","x-zoo"}},
}; //struct {const char* ext;const char* type;} mimes[]


/* like strcasecmp but second parameter is already lower cased */
static inline int lcmp(const unsigned char* l,const char *r){
	const char c = ((unsigned)*l-'A' < 26) ? *l|32 : *l;
	return (!c&&!*r) ? 0 : (c!=*r) ? c-*r : lcmp(++l,++r);
}

MIMEtype *mime_from_ext(const char *ext){
	/* this would be a "sane" fallback
		static char guess[128]="application/x-";
		strcpy(guess+14,ext);
	*/
	int bot=0, top=(sizeof(mimes))/(sizeof(mimes[0]))-1, i, cmp;
	for (i=top>>1; bot<=top; i=(bot+top)>>1){
		cmp=lcmp(ext,mimes[i].ext);
		if (! cmp) return (MIMEtype *)&mimes[i].type; //match found
		else if (cmp>0) bot=i+1;
		else top=i-1;
	}
	while (*ext){ 
		if (*ext=='.' /*||*ext=='/'*/ ) return mime_from_ext(++ext);
		else ++ext;
	}
	return (MIMEtype *)NULL;//guess;
}

MIMEtype *get_mime(const char *path){
	//TODO - just extension ... basename(path)?
	MIMEtype *t = mime_from_ext(path);
#ifndef NO_MAGIC
	if (t == (MIMEtype *)NULL){
		int fd = open(path,04000);
		if (fd>=0){
			t=mime_from_magic(fd);
			close(fd);
		}
	}
#endif
	return t;
}

#ifdef TEST
#include <string.h>
#include <stdio.h>
int main(int argc, char** argv){

	MIMEtype *t;
	t= get_mime(argv[1]);
	printf("get_mime: %s\t%s/%s\n",argv[1], t->major, t->minor);
}
#endif 
